FROM nginx:alpine 
#better to use stable

#ARGs for basic auth
ARG BASIC_AUTH_USER
ARG PBASIC_AUTH_PASS
#dependencies for basic auth
RUN apk add --no-cache apache2-utils 
RUN htpasswd -cb /etc/nginx/.htpasswd $BASIC_AUTH_USER PBASIC_AUTH_PASS
COPY devops.crt /etc/ssl/certs/devops.crt
COPY devops.key /etc/ssl/private/devops.key
COPY default.conf /etc/nginx/conf.d/default.conf

#Creating static pages
RUN mkdir -p /opt/html/root/ && echo '<!DOCTYPE html><html><body>$(cat /etc/os-release)</body></html>' > /opt/html/root/static.html

RUN echo '<!DOCTYPE html><html><body><pre>$(env)</pre></body></html>' > /opt/html/root/index.html

#ENV DRUPAL_PATH /dp 



CMD ["nginx","-g","daemon off;"]